### ISSUE TITLE
What to do with MNIST_DATA_LOCATION?

### ISSUE THREAD

**Issue by Terminou** [wichtounet/mnist#10]
![image](https://user-images.githubusercontent.com/27548058/64412479-1ce6b980-d098-11e9-93ec-2f40d1a36a26.png)

I am getting a compiler error. Any suggestion?

**Comment by wichtounet** [comment]
Hi, 

MNIST_DATA_LOCATION is set by cmake if you use the cmakelists.txt example.

If you do not use the cmake example, this macro is not present in the library.

**Comment by Terminou** [comment]
As far as I know, Visual Studio does not have CMake support directly. So, how can I load MNIST data without setting CMake on Visual Studio?

**Comment by wichtounet** [comment]
There is really no need to use CMake. Just get rid of this line ;)

**Comment by Terminou** [comment]
This time I get these errors below.
![image](https://user-images.githubusercontent.com/27548058/64476237-26a21700-d195-11e9-9a92-bbca2f2749a6.png)

**Comment by wichtounet** [comment]
Could you update the library and try again? There was indeed a bug in the Windows version. It should be fixed.

**Comment by Terminou** [comment]
It seems okay now. Thanks.

**Comment by wichtounet** [comment]
Awesome :)

**Comment by Terminou** [comment]
One more question? Is this output normal? I think it has to print numbers from 0 to 9.
![image](https://user-images.githubusercontent.com/27548058/64479106-e35a9f00-d1ba-11e9-80bf-c1bddaf61bf6.png)

**Comment by wichtounet** [comment]
It's because C++ is printing uint8_t as char. You need to cast the value to (int) to print it correctly:

```cpp
cout << (int) dataset.training_labels[3];
```

**Comment by Terminou** [comment]
Oh sorry, this is my first time with C++ and thank you for your answer.

**Comment by wichtounet** [comment]
No problem :)

**Comment by Sammed98** [comment]
@Terminou @wichtounet  How did you read the images? I mean if I want to print the 0th training image on my command prompt how do I go about it?

Using `cout << (int) dataset.training_labels[3];` you read the labels, but I am not able to read the image. Could you help me with how to print the 0th training image?

**Comment by wichtounet** [comment]
@Sammed98 The images are simply vector of vector, so dataset.training_images[0] would give you the first image (a vector of 28 * 28 elements. So, if you want the pixel 123 of the second image, you could do dataset.training_images[1][123]

**Comment by Sammed98** [comment]
I tried that. But it gave an error.
![image](https://user-images.githubusercontent.com/25957319/89406403-ba2fef00-d73a-11ea-8211-219bc564ed4f.png)

This is the main.cpp file in the example folder. I added the lines to print the label and an image. But this does not even compile. 
The error is as follows:

![image](https://user-images.githubusercontent.com/25957319/89406504-e51a4300-d73a-11ea-8a24-76eed3bc4e2a.png)

This is only a segment of the error. It goes on and on.
Could you guide me on what I am missing?

**Comment by wichtounet** [comment]
I gave you the answer on my previous message. training_images is a vector
of vector, you cannot print it like this.

cout << dataset.training_images[0][0]

will print the first pixel of the first image, if you want to print
several pixels or several images, then, you will have to loop over it.

>

**Comment by Sammed98** [comment]
Thanks a lot. I understood my mistake.
