### ISSUE TITLE
How to convert dataset.test_images to float vector?

### ISSUE THREAD

**Issue by Terminou** [wichtounet/mnist#11]
I am using a library called frugally deep in order to load and predict MNIST data. To predict MNIST data I may need float vector. But the data.test_images has the type below:

> class std::vector<class std::vector<unsigned char,class std::allocator<unsigned char> >,class std::allocator<class std::vector<unsigned char,class std::allocator<unsigned char> > > >

If I successfully convert it to float vector, I guess I will be able to use predict. A sample use of the library I mentioned is given below.

![image](https://user-images.githubusercontent.com/27548058/64512036-33864e00-d2ee-11e9-8ef5-0bcf327758dd.png)

You may also check README.md 

[https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-fill-an-fdeeptensor5-with-values-eg-from-an-stdvectorfloat](url)

**Comment by wichtounet** [comment]
Hi Terminou, 

It should be fairly easy to convert that. The structure is a vector of vector of unsigned char. The first vector contains one subvector for each image. 

What are the five dimensions of tensor5? I would guess (Images, Channels, Widht, Height) but I don't know what is the fifth one and the order. 

It's probably going to be (60'000, 1, 1, 28, 28) or something equivalent.
