### ISSUE TITLE
Potentially missing #include <string>

### ISSUE THREAD

**Issue by Legorock** [wichtounet/mnist#3]
Hi, 
Is there a specific reason why no `<string>` headers included with `mnist_reader.hpp` and `mnist_reader_less.hpp`? I know for most compilers it is included under `<iostream>` but maybe it is better not to rely on standard library implementation details?
Just a thought,
Cheers!

**Comment by wichtounet** [comment]
Hi, 

You're absolutely right, it's missing. 

This is now fixed via afd69443a8c97b070270ef91b225008417d19992

Thanks :)

Baptiste

**Comment by wichtounet** [comment]
I consider the issue fixed, don't hesitate to open again if you feel the need.
