### ISSUE TITLE
Multiple warnings due to invalid casting

### ISSUE THREAD

**Issue by savoptik** [wichtounet/mnist#7]
I tried to compile mnist_reader.hpp and found errors like this:
It's because in the source code you can find the following castings that I believe to be invalid
```+cpp
         if (limit > 0 && count > limit) {
-            count = limit;
+            count = static_cast<unsigned int>(limit);
         }
```
I'll contribute PR for this a bit later. If you can't merge it immediately please suggest how to fix this PR. Thanks.

**Comment by wichtounet** [comment]
Hi savoptik, 

Thanks for reporting that. 

Can you tell with which compiler did you use to get a warning. And can you show the entire warning message from the compiler?

Thanks

**Comment by savoptik** [comment]
Apple LLVM 10.0 from apple Xcode.
./mnist_reader.hpp:92:21: Implicit conversion loses integer precision: 'std::size_t' (aka 'unsigned long') to 'unsigned int'
And these warnings are about 6 PIECES.
Отправлено с Mac
